"""Write docs/metrics.md, the definition of every detection metric, from the code's constants.

The document states each metric in its source notation with a symbol table, the
reason it is computed that way and the function that computes it. Every value it
quotes (the validation size, the rate targets, the quantile ladder, the bars, the
bootstrap settings) is read here from the constant that defines it, so the
document cannot disagree with the code it describes. It quotes no result, since
results change with every sweep and live in results/all_numbers/ and the 2
notebooks it points to.

    PYTHONPATH=. python scripts/metrics_doc.py
"""

import argparse
import json
import os

from data.splits import PSBD_HELDOUT_SIZE, PSBD_SPLIT_SEED
from defenses.decision import (
    ADAPTIVE_SHIFT_TARGET,
    HEADLINE_QUANTILE,
    PLACEMENT_MATCH_TARGET,
    PSBD_QUANTILES,
    PUBLISHED_PLACEMENT,
    RECOMMENDED_PLACEMENT,
)
from detectors import DETECTOR_NAMES
from scripts.coverage_ledger import DIVERGENCE_FRACTION, SOURCE_MAPPED_ACCURACY
from scripts.paper._common import BOOTSTRAP_RESAMPLES, BOOTSTRAP_SEED

DEFAULT_OUT = os.path.join("docs", "metrics.md")
DEFAULT_DECLARATION = os.path.join("configs", "psbd_basis.json")
# The 2 false-positive budgets the paper reports TPR at.
REPORTED_BUDGETS = (0.10, 0.20)

TEMPLATE = r"""# Detection metrics

Generated by `scripts/metrics_doc.py` from the constants it names. Do not edit by hand.

This document defines every number a detection table in this repository reports, from the raw per-pass probabilities on disk to a mean over models with its interval. Each section gives the formula in the notation of its source, a symbol table, the reason it is computed that way and the file and function that compute it. Every value quoted here is read by `scripts/metrics_doc.py` from the constant that defines it, and no result is quoted. The results are in `results/all_numbers/all_numbers.csv`, which `scripts/all_numbers.py` writes. `notebooks/how-every-number-is-computed.ipynb` recomputes each stage on real models while `notebooks/all-numbers.ipynb` lays out every reading.

## The pipeline and its files

The pipeline has 2 stages so that the expensive half runs once. `cli.sweep` runs on a GPU, runs each model once unperturbed and $k$ times perturbed per rate, and writes raw tensors under `results/<folder>/psbd/`. `cli.analyze` runs on a CPU, reads those tensors and writes every metric into `results/<folder>/psbd_metrics.json`. With raw tensors on disk a scoring rule, a quantile or a rate rule can be changed and recomputed in seconds, which is why no metric is computed inside the GPU job. The competitor detectors write 1 record each under `results/<folder>/detectors/` through `cli.baselines`, on the same split and quantiles.

A placement names where a perturbation is injected (the position) and what it does there (the operator). PSBD-TM is `@@RECOMMENDED@@`, token masking at the attention input of every block, the placement the paper recommends. PSBD-RD is `@@PUBLISHED@@`, dropout after both residual additions of every block, our adaptation of the site Li et al. used in a ResNet.

## The PSBD split

The test set of a dataset is shuffled once by `data.splits.psbd_split_permutation` with seed `PSBD_SPLIT_SEED` = @@SPLIT_SEED@@. The first `PSBD_HELDOUT_SIZE` = @@HELDOUT@@ images are the clean validation set, the only data the defender holds. Every threshold and rate choice reads them alone. The rest is the analysis pool: the clean split holds its images as they are, and the backdoor split holds the images the attack may act on (every class but the target for all-to-one, the source classes for TaCT, every non-target class for a clean-label attack), stamped with the trigger. `defenses.decision.pair_clean_to_backdoor` restricts the clean scores to the images behind the backdoor rows, so every triggered image is compared with its own clean copy and the 2 populations differ by the trigger alone. The seed depends on the dataset only, so every model of a dataset sees the identical split.

## Perturbed passes

`models.positions.plug_dropout` attaches a fresh perturbation module at the named position of every block, and the model is run $k$ times with it. A fresh module is used because switching the model's own trained dropout back on would mix its regularization with the probe. The panel uses $k$ = @@PASSES@@ (`panel.forward_passes` in `configs/psbd_basis.json`), the value Li et al. use. For every placement, rate and split `cli.sweep` writes 2 tensors of shape $(k, n)$: the probability each pass gives to the class the unperturbed model predicted, and each pass's own argmax.

## Shift ratio

Li et al. measure the strength of a perturbation by how often it changes the predicted class. With the per-pass prediction shift of image $x$

$$
\phi_{PS}(x; \theta_i') = \mathbb{I}\big(Y(x; \theta) \neq Y(x; \theta_i')\big)
$$

the shift ratio of a set $D$ is

$$
\sigma(D) = \frac{1}{k\,|D|} \sum_{x \in D} \sum_{i=1}^{k} \phi_{PS}(x; \theta_i')
$$

| symbol | meaning |
|---|---|
| $x$ | an input image |
| $\theta$ | the unperturbed model |
| $\theta_i'$ | the model on perturbed pass $i$ |
| $Y(x; \theta)$ | the argmax class of the softmax |
| $\mathbb{I}(\cdot)$ | 1 when the condition holds and 0 otherwise |
| $k$ | perturbed passes per image |
| $D$ | a set of images, the clean validation set when a rate is chosen |
| $\sigma(D)$ | the share of all (image, pass) predictions that moved |

A shared rate is a different intervention at different placements, since dropping a share $p$ of the residual stream in every block leaves $(1 - p)^L$ of it after $L$ blocks while masking the same share of tokens at 1 sublayer input leaves far more. $\sigma$ measures the disturbance on the defender's clean data, so placements are compared at a shared $\sigma$. `defenses.scores.shift_ratio` computes it and `cli.analyze` stores it per split and rate under `shift_ratio`.

## Prediction shift uncertainty

PSU asks how far the probability of the model's own unperturbed answer falls under the perturbation. In Li et al.'s notation

$$
\phi_{PSU}(x) = P_c(x; \theta) - \frac{1}{k} \sum_{i=1}^{k} P_c(x; p, \theta_i'), \qquad c = \arg\max_{c'} P_{c'}(x; \theta)
$$

| symbol | meaning |
|---|---|
| $P_c(x; \theta)$ | softmax probability of class $c$ under the unperturbed model |
| $P_c(x; p, \theta_i')$ | the same probability on pass $i$ at rate $p$ |
| $c$ | the unperturbed argmax, held fixed over the passes |
| $\phi_{PSU}(x)$ | the absolute PSU of image $x$ |

A backdoored model sends a triggered image to its target through a path the perturbation does not break, so the probability holds and the score is low. A low score means poisoned for PSBD and for every competitor, each of which negates its statistic at most once at its own boundary to follow this convention. `defenses.scores.psu_from_cache` computes the absolute form and `cli.analyze` reports its metrics under `detection`.

## Fractional PSU

Every headline number uses the fractional form, the fall as a share of the starting probability,

$$
\phi_{ratio}(x) = 1 - \frac{1}{k} \sum_{i=1}^{k} \frac{P_c(x; p, \theta_i')}{P_c(x; \theta)}
$$

with the symbols above and $P_c(x; \theta)$ clamped below by a small floor in `defenses.scores.psu_ratio_from_cache`. It is chosen over the absolute form for 2 reasons. It removes the objection that PSU measures starting confidence, since dividing by that confidence would destroy a signal that came from it. And it is scale free, so a quantile threshold on it does not inherit the calibration of the validation set. `cli.analyze.analyze_one_rate` reports its metrics under `detection_psu_ratio`, the block every table reads.

The per-input shift ratio $\sigma(x) = \frac{1}{k} \sum_{i} \phi_{PS}(x; \theta_i')$ is not used as a score. It takes $k + 1$ values, so it cannot rank the many images that share one, and it ignores a fall in probability that keeps the argmax. The walkthrough notebook measures both effects on every panel model.

## Rate rules

Every placement is swept over a ladder of rates $\mathcal{P}$, and 1 rate is chosen per model and placement from the clean validation shift ratio alone.

$$
p_{adapt} = \min\{\, p \in \mathcal{P} : \sigma_p(D_{val}) \ge \sigma^\ast_{adapt} \,\}, \qquad
p_{match} = \arg\min_{p \in \mathcal{P}} \big|\sigma_p(D_{val}) - \sigma^\ast_{match}\big|
$$

| symbol | meaning |
|---|---|
| $\mathcal{P}$ | the swept rate ladder of the placement |
| $\sigma_p(D_{val})$ | the shift ratio of the clean validation set at rate $p$ |
| $\sigma^\ast_{adapt}$ | `ADAPTIVE_SHIFT_TARGET` = @@ADAPTIVE@@ |
| $\sigma^\ast_{match}$ | `PLACEMENT_MATCH_TARGET` = @@MATCHED@@ |
| $p_{adapt}, p_{match}$ | the rates the adaptive and the matched rule choose |

The adaptive rule (`defenses.decision.select_rate_adaptively`) is the half of Li et al.'s rule that transfers to a clean test pool, the rate where the clean validation shift ratio reaches their target. It takes the smallest such rate because a larger one destroys more clean evidence for no gain the defender can see, and it returns nothing when no swept rate reaches the target, which `scripts/all_numbers.py` records as `shift_target_unreached`. It is the deployable rule and every headline number uses it. The matched rule (`select_rate_at_matched_shift`) breaks ties toward the smaller rate and exists only to compare placements at the same measured disturbance, at a lower target because at the adaptive target the destructive placements saturate. `cli.compare_detectors.psbd_rate` reads the chosen rate from `psbd_metrics.json`, and `psbd_values` returns that rate's `detection_psu_ratio` block.

## Threshold, TPR and realized FPR

$$
\tau_q = Q_q\big(\{\phi(x) : x \in D_{val}\}\big), \qquad
\mathrm{TPR}_q = \frac{1}{|D_{bd}|} \sum_{x \in D_{bd}} \mathbb{I}\big(\phi(x) < \tau_q\big), \qquad
\mathrm{FPR}_q = \frac{1}{|D_{cl}|} \sum_{x \in D_{cl}} \mathbb{I}\big(\phi(x) < \tau_q\big)
$$

| symbol | meaning |
|---|---|
| $\phi(x)$ | the score, fractional PSU for PSBD |
| $Q_q$ | the empirical $q$ quantile with numpy's linear interpolation |
| $q$ | the false-positive budget, on `PSBD_QUANTILES` = @@QUANTILES@@ |
| $D_{val}$ | the clean validation images |
| $D_{bd}$ | the triggered images |
| $D_{cl}$ | the paired clean copies of the triggered images |
| $\tau_q$ | the threshold, strictly below which an image is flagged |

The threshold reads clean data only, so the quantile is the budget the defender sets. The paper reports TPR at the @@BUDGETS@@ budgets. `HEADLINE_QUANTILE` = @@HEADLINE_QUANTILE@@ is Li et al.'s own quantile and keys the headline blocks. The realized FPR is measured on the paired clean images and differs from $q$ through sampling and because the paired images exclude the target class, or keep only TaCT's source class. `defenses.decision.threshold_at_quantile` and `detection_report` compute these for PSBD and every competitor alike.

## AUROC

$$
\mathrm{AUROC} = \frac{1}{|D_{bd}|\,|D_{cl}|} \sum_{x \in D_{bd}} \sum_{x' \in D_{cl}} \Big( \mathbb{I}\big(\phi(x) < \phi(x')\big) + \tfrac{1}{2}\, \mathbb{I}\big(\phi(x) = \phi(x')\big) \Big)
$$

with the symbols above. It is the probability that a random triggered image scores below a random paired clean image, computed by `detection_report` with scikit-learn's `roc_auc_score` on the negated scores. The AUROC is one-sided: the direction is fixed before the data is seen, a value below one half means the defense ordered the 2 populations the wrong way round on that model, and it enters every mean as it is. The two-sided form $\max(A, 1 - A)$ needs the labels to pick a side, so it is kept only as the diagnostic field `auroc_two_sided`, which no table reads. AUROC does not depend on the threshold, so every quantile block of a record carries the same value. A model can read a high AUROC and a low TPR when its paired images come from a population the validation quantile does not describe, as TaCT's single source class does.

## Success bars

`scripts/coverage_ledger.py` gives every panel model an `asr_class`. It is `clears` at an ASR of at least `asr_bar` = @@ASR_BAR@@ and `below_bar` under it. `diverged` overrides it when the clean accuracy is below `DIVERGENCE_FRACTION` = @@DIVERGENCE@@ of the benign reference, a collapsed run. `source_mapped` overrides it when the clean accuracy on a TaCT model's source classes is below `SOURCE_MAPPED_ACCURACY` = @@SOURCE_MAPPED@@, a class mapping that needs no trigger. The success verdicts are added beside `asr_class` by `success_verdicts`:

$$
\text{successful}_b = \big[\,\text{asr\_class} = \text{clears}\,\big] \wedge \big[\,\Delta CA \ge b\,\big]
$$

| symbol | meaning |
|---|---|
| $\Delta CA$ | `clean_accuracy_drop`, the model's clean accuracy minus the benign reference's, negative when the attack cost accuracy |
| $b$ | `clean_accuracy_drop_bar_headline` = @@HEADLINE_BAR@@ for `successful_2pt`, `clean_accuracy_drop_bar` = @@SECOND_BAR@@ for `successful_5pt` |

A backdoor that costs visible clean accuracy is a backdoor a defender could catch by accuracy alone, so the headline success definition allows the smaller drop and every number is also given at the larger one. `asr_class` itself is left unchanged because the paper generators select on it.

## Paired gain and bootstrap interval

2 defenses are compared on the models that carry both, paired within a model so that the variation between models cancels:

$$
\Delta_m = A_m^{1} - A_m^{2}, \qquad \bar{\Delta} = \frac{1}{M} \sum_{m=1}^{M} \Delta_m, \qquad \bar{\Delta}^{(b)} = \frac{1}{M} \sum_{j=1}^{M} \Delta_{m_{b,j}}
$$

| symbol | meaning |
|---|---|
| $A_m^{1}, A_m^{2}$ | the 2 defenses' one-sided AUROC (or TPR) on model $m$ |
| $M$ | models carrying both readings |
| $m_{b,j}$ | the $j$th model drawn with replacement in resample $b$ |
| $\bar{\Delta}^{(b)}$ | the mean difference on resample $b$ |
| $B$ | resamples, `BOOTSTRAP_RESAMPLES` = @@RESAMPLES@@, seeded with `BOOTSTRAP_SEED` = @@SEED@@ |

The 95% interval is the percentile interval of the sorted $\bar{\Delta}^{(b)}$, from `scripts/paper/_common.bootstrap_ci`. The resampling unit is the model, so the interval covers the choice of trained models and not the sampling error inside an AUROC or the training seed. The resampler draws positions in a list, so under the fixed seed the interval depends on the order the models are listed in at the third decimal: `scripts/paper/tab_headline.py` lists them by folder name and `scripts/paper/tab_detectors.py` by dataset, attack and rate.

## Rank and margin

The competitor comparison reads PSBD-TM, PSBD-RD and the @@DETECTORS@@ detectors of `detectors.DETECTOR_NAMES` on the models where every one has a reading, at the adaptive rule for PSBD. Per metric (AUROC, TPR at each reported budget) `scripts/paper/tab_detectors.metric_macros` sorts the means in descending order: PSBD-TM's rank is its position, PSBD-RD's rank is 1 plus the number of defenses with a strictly higher mean, and the margin is PSBD-TM's mean minus the mean of the strongest competitor detector, with the paired bootstrap interval above.

## The columns of the all-numbers table

`results/all_numbers/all_numbers.csv` holds 1 row per (model, defense) and every column below. The JSON beside it adds the list of models and the bars.

| column | meaning |
|---|---|
| `architecture`, `folder_name`, `kind`, `in_panel` | the model, whether it is an attacked or a benign model and whether the panel rule selects it |
| `dataset`, `attack`, `label_mode`, `poison_rate`, `realized_poison_rate`, `target_label` | the training run, from `checkpoints/<folder>/args.json` through the ledger |
| `asr`, `clean_accuracy`, `clean_accuracy_benign`, `clean_accuracy_drop` | attack success, clean accuracy, the benign reference and $\Delta CA$ |
| `asr_class`, `diverged`, `source_mapped`, `source_class_accuracy` | the ledger verdicts |
| `successful_2pt`, `successful_5pt` | the success verdicts |
| `audit_note` | set on rows kept but under audit, currently every SIG row |
| `defense`, `family`, `placement`, `rule` | PSBD-TM, PSBD-RD, `PSBD <placement>` or a detector name, with the PSBD rate rule |
| `status` | `scored`, `shift_target_unreached`, `failed` or `smoke` |
| `rate`, `validation_shift_ratio` | the chosen rate and the clean validation shift ratio there |
| `auroc`, `auroc_absolute_psu` | the one-sided AUROC of the score, and of absolute PSU for PSBD |
| `tpr_q0.10` to `fpr_q0.25` | TPR and realized FPR at each reported quantile |
| `n_backdoor` | triggered images behind the reading |
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--declaration", default=DEFAULT_DECLARATION)
    parser.add_argument("--out", default=DEFAULT_OUT)
    return parser.parse_args()


def load_declaration(path: str) -> dict:
    """The basis declaration read from path."""
    with open(path) as handle:
        declaration = json.load(handle)
    return declaration


def fill_template(declaration: dict) -> str:
    """The document text with every @@NAME@@ replaced by the constant it names."""
    values = {
        "RECOMMENDED": RECOMMENDED_PLACEMENT,
        "PUBLISHED": PUBLISHED_PLACEMENT,
        "SPLIT_SEED": str(PSBD_SPLIT_SEED),
        "HELDOUT": str(PSBD_HELDOUT_SIZE),
        "PASSES": str(declaration["panel"]["forward_passes"]),
        "ADAPTIVE": f"{ADAPTIVE_SHIFT_TARGET}",
        "MATCHED": f"{PLACEMENT_MATCH_TARGET}",
        "QUANTILES": ", ".join(f"{quantile:.2f}" for quantile in PSBD_QUANTILES),
        "BUDGETS": " and ".join(f"{budget:.2f}" for budget in REPORTED_BUDGETS),
        "HEADLINE_QUANTILE": f"{HEADLINE_QUANTILE}",
        "ASR_BAR": f"{declaration['asr_bar']}",
        "DIVERGENCE": f"{DIVERGENCE_FRACTION}",
        "SOURCE_MAPPED": f"{SOURCE_MAPPED_ACCURACY}",
        "HEADLINE_BAR": f"{declaration['clean_accuracy_drop_bar_headline']}",
        "SECOND_BAR": f"{declaration['clean_accuracy_drop_bar']}",
        "RESAMPLES": str(BOOTSTRAP_RESAMPLES),
        "SEED": str(BOOTSTRAP_SEED),
        "DETECTORS": str(len(DETECTOR_NAMES)),
    }
    text = TEMPLATE
    for name, value in values.items():
        text = text.replace(f"@@{name}@@", value)
    assert "@@" not in text, "a placeholder in the template has no value"
    return text


def write_document(path: str, text: str) -> None:
    """Write the document, creating its directory first."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as handle:
        handle.write(text)


def main() -> None:
    args = parse_args()
    declaration = load_declaration(args.declaration)
    text = fill_template(declaration)
    write_document(args.out, text)
    print(f"[ok] {args.out}")


if __name__ == "__main__":
    main()
